version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: ./app
    command: gunicorn booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: mdillon/postgis:10-alpine 
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgis_data:
  static_volume:
