# Generated by Django 3.0.4 on 2020-04-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20200406_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_flujo', models.CharField(choices=[('inicio', 'Inicio del Flujo'), ('condicional', 'Pregunta condicional'), ('normal', 'Flujo normal'), ('fin', 'Termina la encuesta')], max_length=20)),
                ('fin_de_seccion', models.IntegerField(choices=[(1, 'Ultima pregunta de la seccion'), (0, 'Mostrar siguiente pregunta en misma seccion')], default=0)),
                ('pregunta_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_actual', to='home.Pregunta')),
                ('siguiente_pregunta_en_flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_siguiente', to='flujo.Flujo')),
            ],
        ),
    ]
