# Generated by Django 3.0.4 on 2020-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='es_condicional',
            field=models.IntegerField(choices=[(1, 'Es una pregunta condicional. Automáticamente se convierte en final de seccioón'), (0, 'No es una pregunta condicional')], default=0),
        ),
    ]
