# Generated by Django 3.0.4 on 2020-04-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_flujo_es_condicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='siguiente_pregunta_en_flujo_negativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_siguiente_flujo_negativo', to='flujo.Flujo'),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='tipo_flujo',
            field=models.CharField(choices=[('inicio', 'Inicio del Flujo'), ('normal', 'Flujo normal'), ('fin', 'Termina la encuesta')], max_length=20),
        ),
    ]
