# Generated by Django 3.0.4 on 2020-04-04 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_input',
            field=models.CharField(choices=[('radio', 'Respuesta unica'), ('checkbox', 'Multiples respuestas')], default='radio', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha creacion'),
        ),
    ]
