# Generated by Django 3.0.4 on 2020-04-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200404_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_input',
            field=models.CharField(choices=[('radio', 'Respuesta unica'), ('checkbox', 'Multiples respuestas'), ('email', 'Correo electronico'), ('tel', 'Telefono')], max_length=20),
        ),
    ]
