# Generated by Django 3.0.4 on 2020-04-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200406_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='es_positiva',
            field=models.IntegerField(default=1),
        ),
    ]
