# Generated by Django 3.0.4 on 2020-04-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_opcion_es_positiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='es_positiva',
            field=models.IntegerField(default=0),
        ),
    ]
