# Generated by Django 3.0.4 on 2020-04-10 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200410_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='hora_encuesta_iniciada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha inicio encuesta'),
            preserve_default=False,
        ),
    ]
