# Generated by Django 3.0.4 on 2020-04-10 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_respuesta_hora_encuesta_iniciada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha creacion')),
                ('hora_encuesta_iniciada', models.DateTimeField(verbose_name='fecha inicio encuesta')),
            ],
        ),
    ]
