# Generated by Django 3.0.4 on 2020-04-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_datospersonales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
