# Generated by Django 3.0.4 on 2020-04-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200411_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='nombre',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='cedula',
            new_name='telefono',
        ),
    ]
