# Generated by Django 3.0.4 on 2020-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200412_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.CharField(max_length=4),
        ),
    ]
