name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted 
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      SQL_ENGINE: django.contrib.gis.db.backends.postgis
      SQL_DATABASE: hello_django_dev
      SQL_USER: hello_django
      SQL_PASSWORD: hello_django
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SECRET_KEY: change_me
      DEBUG: 1

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.github.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs backend
      run: docker logs backend 
    - name: Check logs db
      run: docker logs db 
    - name: Run test suite
      run: docker exec backend python manage.py test
